import localFont from "next/font/local";
import "./globals.css";
import Header from "Components/Header";
import Intro from "Components/Intro";
import Cards from "Components/Cards";
import Offers from "Components/Offers";
import Overview from "Components/Overview";
import Level from "Components/Level";
import Faqs from "Components/Faqs";
import Footer from "Components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Ayatrio app",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#F3E3C5]`}
      >
        <div className="w-[90%] m-auto">
          {children}
          <Header />
          <Intro />
          <Cards />
          <Offers />
          <Overview />
          <Level />
          <Faqs />
          <Footer />

        </div>


      </body>
    </html>
  );
}


